#!/bin/bash

function usage
{
    echo "usage: copyTestFiles [-d] <filename>"
}

##### Main

db=
file=

while [ "$1" != "" ]; do
    case $1 in
        -d | --database )       db=1
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     file=$1
    esac
    shift
done

if [ "$file" = "" ]; then
	usage
	exit 1
else
	cp -v ./data.json ${file}
	if [ "$db" = "1" ]; then
		cp -v ./db.json db${file}
	fi
fi

