/*
*
*           RaphaëlTools : Raphaël extension (button, sliders, ...)         
*                                                                             
*                            version 0.8 (2014-08-20)                         
*  
*                    Copyright (C)  2011 - 2014  Jan Stransky                 
*  
*           Czech Technical University, Faculty of Civil Engineering,         
*       Department of Structural Mechanics, 166 29 Prague, Czech Republic     
*  
*  RaphaëlTools is free software: you can redistribute it and/or modify it
*  under the terms of the GNU Lesser General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or (at your
*  option) any later version.
*  
*  RaphaëlTools is distributed in the hope that it will be useful, but
*  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
*  or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
*  License for more details.
*  
*  You should have received a copy of the GNU Lesser General Public License
*  along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
var RaphaelTools={},onDragMove=function(a,b){var d=Raphael.raphaeltoolsDrawingUnit||1;this.onDragUpdate(1/d*(a-(this.deltax||0)),1/d*(b-(this.deltay||0)));this.deltax=a;this.deltay=b},onDragStart=function(){this.deltax=this.deltay=0},onDragStop=function(){this.onDragStop()};Raphael.el.fillRed=function(){return this.attr({fill:"#f00"})};Raphael.el.fillGreen=function(){return this.attr({fill:"#0f0"})};Raphael.el.fillBlue=function(){return this.attr({fill:"#00f"})};Raphael.el.fillYellow=function(){return this.attr({fill:"#ff0"})};
Raphael.el.fillCyan=function(){return this.attr({fill:"#0ff"})};Raphael.el.fillMagenta=function(){return this.attr({fill:"#f0f"})};Raphael.el.fillOrange=function(){return this.attr({fill:"#f50"})};Raphael.el.fillBlack=function(){return this.attr({fill:"#000"})};Raphael.el.fillWhite=function(){return this.attr({fill:"#fff"})};Raphael.el.fillGray=function(){return this.attr({fill:"#777"})};Raphael.el.strokeRed=function(){return this.attr({stroke:"#f00"})};Raphael.el.strokeGreen=function(){return this.attr({stroke:"#0f0"})};
Raphael.el.strokeBlue=function(){return this.attr({stroke:"#00f"})};Raphael.el.strokeYellow=function(){return this.attr({stroke:"#ff0"})};Raphael.el.strokeCyan=function(){return this.attr({stroke:"#0ff"})};Raphael.el.strokeMagenta=function(){return this.attr({stroke:"#f0f"})};Raphael.el.strokeOrange=function(){return this.attr({stroke:"#f50"})};Raphael.el.strokeBlack=function(){return this.attr({stroke:"#000"})};Raphael.el.strokeWhite=function(){return this.attr({stroke:"#fff"})};
Raphael.el.strokeGray=function(){return this.attr({stroke:"#777"})};Raphael.el.red=function(){this.fillRed();return this.strokeRed()};Raphael.el.green=function(){this.fillGreen();return this.strokeGreen()};Raphael.el.blue=function(){this.fillBlue();return this.strokeBlue()};Raphael.el.yellow=function(){this.fillYellow();return this.strokeYellow()};Raphael.el.cyan=function(){this.fillCyan();return this.strokeCyan()};Raphael.el.magenta=function(){this.fillMagenta();return this.strokeMagenta()};
Raphael.el.orange=function(){this.fillOrange();return this.strokeOrange()};Raphael.el.black=function(){this.fillBlack();return this.strokeBlack()};Raphael.el.white=function(){this.fillWhite();return this.strokeWhite()};Raphael.el.gray=function(){this.fillGray();return this.strokeGray()};Raphael.el.stroke=function(a){return this.attr({stroke:a})};Raphael.el.fill=function(a){return this.attr({fill:a})};Raphael.el.setWidth=function(a){return this.attr({"stroke-width":a})};
RaphaelTools.vecTrans=function(a,b,d,c){return[a*c-b*d,a*d+b*c]};RaphaelTools.Point2d=function(a,b){this.x=a||0;this.y=b||0;this.copies=[];this.copiesShifts=[]};RaphaelTools.Point2d.prototype.toString=function(){return"Point2d ( "+this.x+","+this.y+" )"};RaphaelTools.Point2d.prototype.copy=function(a){for(var b=0;b<a.length;b++)this.copiesShifts.push(a[b]),this.copies.push(RaphaelTools.Point2d.create(this.x+a[b][0],this.y+a[b][1]))};
RaphaelTools.Point2d.prototype.setXY=function(a,b){this.x=a;this.y=b;this.update()};RaphaelTools.Point2d.prototype.setX=function(a){this.x=a;this.update()};RaphaelTools.Point2d.prototype.setY=function(a){this.y=a;this.update()};RaphaelTools.Point2d.prototype.translate=function(a,b){this.x+=a;this.y+=b;this.update()};RaphaelTools.Point2d.prototype.translateX=function(a){this.translate(a,0)};RaphaelTools.Point2d.prototype.translateY=function(a){this.translate(0,a)};
RaphaelTools.Point2d.prototype.update=function(){for(var a=0;a<this.copies.length;a++)this.copies[a].setXY(this.x+this.copiesShifts[a][0],this.y+this.copiesShifts[a][1]),this.copies[a].update()};RaphaelTools.Point2d.create=function(a,b){var d=new RaphaelTools.Point2d(a,b);d.update();return d};
RaphaelTools.Point3d=function(a,b,d,c){this.xr=a||0;this.yr=b||0;this.zr=d||0;this.copies=[];this.copiesShifts=[];this.p=void 0==c?[[1,0,0],[0,1,0],[0,0,1]]:c;this.x=this.p[0][0]*this.xr+this.p[0][1]*this.yr+this.p[0][2]*this.zr+(this.p[0][3]||0);this.y=this.p[1][0]*this.xr+this.p[1][1]*this.yr+this.p[1][2]*this.zr+(this.p[1][3]||0);this.z=this.p[2][0]*this.xr+this.p[2][1]*this.yr+this.p[2][2]*this.zr+(this.p[2][3]||0)};
RaphaelTools.Point3d.prototype.toString=function(){return"Point3d ( "+this.xr+","+this.yr+","+this.zr+" )"};RaphaelTools.Point3d.prototype.copy=function(a){for(var b=0;b<a.length;b++)this.copiesShifts.push(a[b]),this.copies.push(new RaphaelTools.Point3d(this.xr+a[b][0],this.yr+a[b][1],this.zr+a[b][2]))};RaphaelTools.Point3d.prototype.setXYZ=function(a,b,d){this.xr=a;this.yr=b;this.zr=d;this.update()};RaphaelTools.Point3d.prototype.setX=function(a){this.xr=a;this.update()};
RaphaelTools.Point3d.prototype.setY=function(a){this.yr=a;this.update()};RaphaelTools.Point3d.prototype.setZ=function(a){this.zr=a;this.update()};RaphaelTools.Point3d.prototype.translate=function(a,b,d){this.xr+=a;this.zr+=d;this.yr+=b;this.update()};RaphaelTools.Point3d.prototype.translateX=function(a){this.translate(a,0,0)};RaphaelTools.Point3d.prototype.translateY=function(a){this.translate(0,a,0)};RaphaelTools.Point3d.prototype.translateZ=function(a){this.translate(0,0,a)};
RaphaelTools.Point3d.prototype.setProjection=function(a){this.p=a;this.update()};RaphaelTools.Point3d.prototype.project=function(){this.x=this.p[0][0]*this.xr+this.p[0][1]*this.yr+this.p[0][2]*this.zr+(this.p[0][3]||0);this.y=this.p[1][0]*this.xr+this.p[1][1]*this.yr+this.p[1][2]*this.zr+(this.p[1][3]||0);this.z=this.p[2][0]*this.xr+this.p[2][1]*this.yr+this.p[2][2]*this.zr+(this.p[2][3]||0)};
RaphaelTools.Point3d.prototype.rotX=function(a){var b=Math.cos(a);a=Math.sin(a);var d=this.p,c=d[1][0],f=d[1][1],e=d[1][2],g=d[2][0],h=d[2][1],m=d[2][2];d[1][0]=c*b-g*a;d[2][0]=c*a+g*b;d[1][1]=f*b-h*a;d[2][1]=f*a+h*b;d[1][2]=e*b-m*a;d[2][2]=e*a+m*b;this.update()};
RaphaelTools.Point3d.prototype.rotY=function(a){var b=Math.cos(a);a=Math.sin(a);var d=this.p,c=d[0][0],f=d[0][1],e=d[0][2],g=d[2][0],h=d[2][1],m=d[2][2];d[0][0]=c*b-g*a;d[2][0]=c*a+g*b;d[0][1]=f*b-h*a;d[2][1]=f*a+h*b;d[0][2]=e*b-m*a;d[2][2]=e*a+m*b;this.update()};
RaphaelTools.Point3d.prototype.rotZ=function(a){var b=Math.cos(a);a=Math.sin(a);var d=this.p,c=d[0][0],f=d[0][1],e=d[0][2],g=d[1][0],h=d[1][1],m=d[1][2];d[0][0]=c*b-g*a;d[1][0]=c*a+g*b;d[0][1]=f*b-h*a;d[1][1]=f*a+h*b;d[0][2]=e*b-m*a;d[1][2]=e*a+m*b;this.update()};RaphaelTools.Point3d.prototype.update=function(){this.project();for(var a=0;a<this.copies.length;a++)this.copies[a].setXYZ(this.xr+this.copiesShifts[a][0],this.yr+this.copiesShifts[a][1],this.zr+this.copiesShifts[a][2]),this.copies[a].update()};
RaphaelTools.Point3d.create=function(a,b,d,c){a=new RaphaelTools.Point3d(a,b,d,c);a.update();return a};
Raphael.fn.LineSegment=function(a,b,d){d=void 0==d?{}:d;d=this.path().attr(d);d.point1=a;d.point2=b;d.copies=[];d.copiesPoints=[[],[]];d.update=function(){this.attr({path:[["M",this.point1.x,this.point1.y],["L",this.point2.x,this.point2.y]]});for(var a=0;a<this.copies.length;a++)this.copies[a].update()};d.copy=function(a){for(var b=0;b<a[0].length;b++)this.copiesPoints[0].push(a[0][b]),this.copiesPoints[1].push(a[1][b]),this.copies.push(this.makeCopy(a[0][b],a[1][b]));this.update()};d.makeCopy=function(a,
b){var d=this.paper.LineSegment(a,b);d.attr(this.attr());d.update();return d};d.update();return d};
Raphael.fn.LineBR=function(a,b,d,c,f,e){e=void 0==e?{}:e;e=this.path().attr(e);e.a=void 0==a?1:a;e.b=void 0==b?1:b;e.c=void 0==d?1:d;e.lt=c||RaphaelTools.Point2d.create();e.rb=f||RaphaelTools.Point2d.create();e.point1=RaphaelTools.Point2d.create();e.point2=RaphaelTools.Point2d.create();e.isOutsideBR=!0;e.setABC=function(a,b,c){this.a=a;this.b=b;this.c=c;this.update()};e.setA=function(a){this.a=a;this.update()};e.setB=function(a){this.b=a;this.update()};e.setC=function(a){this.c=a;this.update()};e.findSections=
function(){var a,b,c=this.a,d=this.b,e=this.c,f=this.point1,p=this.point2,n=this.lt;a=this.rb;var k=n.y,l=a.y,n=n.x,q=a.x;this.show();this.isOutsideBR=!1;0==c?-e/d>k&&-e/d<l?(f.setXY(n,-e/d),p.setXY(q,-e/d)):(this.hide(),this.isOutsideBR=!0):0==d?-e/c>n&&-e/c<q?(f.setXY(-e/c,k),p.setXY(-e/c,l)):(this.hide(),this.isOutsideBR=!0):(a=-(c*n+e)/d,b=-(c*q+e)/d,a<k&&b<k?(this.hide(),this.isOutsideBR=!0):a>l&&b>l?(this.hide(),this.isOutsideBR=!0):a>k&&a<l&&b>k&&b<l?(f.setXY(n,a),p.setXY(q,b)):a<k&&b>l||a>
l&&b<k?(f.setXY(-(d*k+e)/c,k),p.setXY(-(d*l+e)/c,l)):a<l&&a>k?(f.setXY(n,a),b<k?p.setXY(-(d*k+e)/c,k):p.setXY(-(d*l+e)/c,l)):(p.setXY(q,b),a<k?f.setXY(-(d*k+e)/c,k):f.setXY(-(d*l+e)/c,l)))};e.normalize=function(){if(1!=this.a*this.a+this.b*this.b){var a=Math.sqrt(this.a*this.a+this.b*this.b);this.a/=a;this.b/=a;this.c/=a}};e.update=function(){this.normalize();this.findSections();this.attr({path:[["M",this.point1.x,this.point1.y],["L",this.point2.x,this.point2.y]]})};e.update();return e};
Raphael.fn.Path=function(a,b){b=void 0==b?{}:b;var d=this.path(a).attr(b);d.pathList=a;d.setItem=function(a,b,d){this.pathList[a][b]=d;this.update()};d.iaddItem=function(a,b,d){this.pathList[a][b]+=d;this.update()};d.setNewPath=function(a){this.pathList=a;this.update()};d.update=function(){this.attr({path:this.pathList})};d.update();return d};
Raphael.fn.Circle=function(a,b,d,c){c=void 0==c?{}:c;c=this.circle(a,b,d).attr(c);c.x=a;c.y=b;c.r=d;c.copies=[];c.copiesShifts=[];c.setR=function(a){this.r=a;this.update()};c.setXYR=function(a,b,c){this.x=a;this.y=b;this.r=c;this.update()};c.setXY=function(a,b){this.x=a;this.y=b;this.update()};c.setX=function(a){this.x=a;this.update()};c.setY=function(a){this.y=a;this.update()};c.translate=function(a,b){this.x+=a;this.y+=b;this.update()};c.translateX=function(a){this.translate(a,0)};c.translateY=
function(a){this.translate(0,a)};c.copy=function(a){for(var b=0;b<a.length;b++)this.copiesShifts.push(a[b]),this.copies.push(this.makeCopy());this.update()};c.makeCopy=function(){var a=this.paper.Circle(0,0,0);a.attr(this.attr());a.update();return a};c.update=function(){this.attr({cx:this.x,cy:this.y,r:this.r});for(var a=0;a<this.copies.length;a++)this.copies[a].setXYR(this.x+this.copiesShifts[a][0],this.y+this.copiesShifts[a][1],this.r)};c.update();return c};
Raphael.fn.SliderCirc=function(a){a=void 0==a?{}:a;var b=this.circle(0,0).attr({fill:"#f00",r:6,"stroke-width":2,cursor:"move"});b.attr(a);b.getX=function(){return this.attr("cx")};b.setX=function(a){this.attr({cx:a})};b.getY=function(){return this.attr("cy")};b.setY=function(a){this.attr({cy:a})};return b};
Raphael.fn.SliderRect=function(a){a=void 0==a?{}:a;a=this.rect(0,0,13,13,3).attr({fill:"#f00",cursor:"move"}).attr(a);a.getX=function(){return this.attr("x")+0.5*this.attr("width")};a.setX=function(a){this.attr({x:a-0.5*this.attr("width")})};a.getY=function(){return this.attr("y")+0.5*this.attr("height")};a.setY=function(a){this.attr({y:a-0.5*this.attr("height")})};return a};
Raphael.fn.Slider=function(a,b){var d=this.path(),c=a?a:this.SliderRect();c.onmove=function(){};c.getVal=function(){var a=this.getX(),b=this.getY(),a=Math.sqrt((a-this.x)*(a-this.x)+(b-this.y)*(b-this.y))-this.start;return this.val1+a*(this.val2-this.val1)/this.lenVals};c.setVal=function(a){a<Math.min(this.val3,this.val4)&&(a=Math.min(this.val3,this.val4));a=this.start+this.lenVals/(this.val2-this.val1)*(a-this.val1);a<this.start?(this.maxFlag=!1,this.minFlag=!0,a=this.start):a>this.stop?(this.maxFlag=
!0,this.minFlag=!1,a=this.stop):this.maxFlag=this.minFlag=!1;this.setX(this.x+a*this.cos);this.setY(this.y+a*this.sin);this.onDragStop()};b=b||{};c.x=void 0==b.x?100:b.x;c.y=void 0==b.y?100:b.y;c.dx=void 0==b.dx?100:b.dx;c.dy=void 0==b.dy?0:b.dy;c.len=Math.sqrt(c.dx*c.dx+c.dy*c.dy);c.cos=c.dx/c.len;c.sin=c.dy/c.len;var f=void 0==b.lineAttrs?{}:b.lineAttrs;c.gap=void 0==b.gap?12:b.gap;c.start=c.gap;c.stop=c.len-c.start;c.val1=void 0==b.val1?0:b.val1;c.val2=void 0==b.val2?1:b.val2;c.val3=void 0==b.val3?
c.val1:b.val3;c.val4=void 0==b.val4?c.val2:b.val4;var e=void 0==b.initVal?0.5*(c.val1+c.val2):b.initVal;c.lenVals=c.len-2*c.start;c.left=c.start+(c.val3-c.val1)/(c.val2-c.val1)*c.lenVals;c.right=c.start+(c.val4-c.val1)/(c.val2-c.val1)*c.lenVals;c.line=d.attr({path:[["M",c.x,c.y],["l",c.dx,c.dy]],stroke:"#000","stroke-width":7}).attr(f);c.attr({cursor:"move"});c.onDragStop=function(){this.posX=this.getX();this.posY=this.getY()};c.onDragStop();c.setVal(e);c.minFlag=!1;c.maxFlag=!1;c.onDragUpdate=function(a,
b){this.posX+=a;this.posY+=b;var c=(this.posX-this.x)*this.cos+(this.posY-this.y)*this.sin;c<this.left?(this.minFlag||(this.setX(this.x+this.left*this.cos),this.setY(this.y+this.left*this.sin),this.onmove()),this.minFlag=!0,this.maxFlag=!1):c>this.right?(this.maxFlag||(this.setX(this.x+this.right*this.cos),this.setY(this.y+this.right*this.sin),this.onmove()),this.minFlag=!1,this.maxFlag=!0):(this.setX(this.x+c*this.cos),this.setY(this.y+c*this.sin),this.maxFlag=this.minFlag=!1,this.onmove())};c.drag(onDragMove,
onDragStart,onDragStop);return c};
Raphael.fn.TextBox=function(a){a=a||{};var b=void 0==a.x?100:a.x,d=void 0==a.y?100:a.y,c=void 0==a.width?100:a.width,f=void 0==a.height?100:a.height,e=void 0==a.str?"string":a.str,g=void 0==a.rectAttrs?{}:a.rectAttrs;a=void 0==a.textAttrs?{}:a.textAttrs;g=this.rect(b,d,c,f).attr(g);g.text=this.text(b+0.5*c,d+0.5*f,e).attr({"font-size":20}).attr(a);g.x=b;g.y=d;g.width=c;g.height=f;g.str=e;g.update=function(){this.attr({x:this.x,y:this.y});this.text.attr({x:this.x+0.5*this.width,y:this.y+0.5*this.height,
text:this.str})};g.setXY=function(a,b){this.x=a;this.y=b;this.update()};g.setX=function(a){this.x=a;this.update()};g.setY=function(a){this.y=a;this.update()};g.setStr=function(a){this.str=a;this.update()};return g};
Raphael.fn.Button=function(a){void 0==a.x&&(a.x=100);void 0==a.y&&(a.y=100);void 0==a.width&&(a.width=100);void 0==a.height&&(a.height=30);void 0==a.r&&(a.r=4);void 0==a.bgColor&&(a.bgColor="#bbb");void 0==a.bgColorWhenClicked&&(a.bgColorWhenClicked="#aaa");var b=this.TextBox(a),d=void 0==a.r?4:a.r;b.cover=this.rect(b.x,b.y,b.width,b.height).attr({fill:"#000",opacity:0,cursor:"pointer"});b.cover.button=b;b.bgColor=void 0==a.bgColor?"#bbb":a.bgColor;b.bgColorWhenClicked=void 0==a.bgColorWhenClicked?
"#aaa":a.bgColorWhenClicked;b.attr({r:d,fill:b.bgColor});b.onClick=function(){};b.doThisWhenClicked=function(){this.text.attr({x:this.x+0.5*this.width+2});this.attr({fill:this.bgColorWhenClicked});this.onClick()};b.doThisWhenUnclicked=function(){this.text.attr({x:this.x+0.5*this.width});this.attr({fill:this.bgColor})};b.cover.mousedown(function(a){this.button.doThisWhenClicked()});b.cover.mouseup(function(a){this.button.doThisWhenUnclicked()});b.cover.mouseout(function(a){this.button.doThisWhenUnclicked()});
return b};
RaphaelTools.Legend=function(a,b,d){this.x=void 0==d.x?0:d.x;this.y=void 0==d.y?0:d.y;this.len=void 0==d.len?100:d.len;this.fontSize=void 0==d.fontSize?15:d.fontSize;this.dy=void 0==d.dy?30:d.dy;for(var c,f,e,g=this.y,h=0;h<b.length;h++)d=b[h][0],c=1<b[h].length?b[h][1]:"#000",f=2<b[h].length?b[h][2]:1,e=3<b[h].length?b[h][3]:{},e["stroke-width"]=f,e.stroke=c,a.path([["M",this.x,g],["l",this.len,0]]).attr(e),a.text(this.x+this.len+20,g,d).attr({"font-size":this.fontSize,"text-anchor":"start"}),g+=
this.dy};RaphaelTools.Legend.create=function(a,b,d){return new RaphaelTools.Legend(a,b,d)};
Raphael.fn.CheckBox=function(a){a=void 0==a?{}:a;var b=void 0==a.x?100:a.x,d=void 0==a.y?100:a.y,c=void 0==a.dim?20:a.dim,f=void 0==a.isChecked?!1:a.isChecked,e=void 0==a.rectAttrs?{}:a.rectAttrs;a=void 0==a.pathAttrs?{}:a.pathAttrs;e=this.rect(b,d,c,c).attr({"stroke-width":2,fill:"#fff"}).attr(e);e.x=b;e.y=d;e.dim=c;e.isChecked=f;e.path=this.path([["M",e.x+0.2*e.dim,e.y+0.4*e.dim],["l",0.2*e.dim,0.3*e.dim],["l",0.4*e.dim,-0.5*e.dim]]).attr({"stroke-width":3}).attr(a);e.isChecked||e.path.hide();e.cover=
this.rect(b,d,c,c).attr({fill:"#000",opacity:0,cursor:"pointer"});e.cover.checkBox=e;e.cover.click(function(){this.checkBox.check(!this.checkBox.isChecked);this.checkBox.onChange()});e.onChange=function(){};e.check=function(a){void 0==a||a?(this.path.show(),this.isChecked=!0):(this.path.hide(),this.isChecked=!1)};e.uncheck=function(){this.check(!1)};return e};
