conn = new Mongo();
db.conn.getDB("myDatabase");
db.images.insert(   [{imgSrc: "../resource/Alba.jpg"},
    {imgSrc: "../resource/littleCat.png"},
    {imgSrc: "../resource/millions.png"},
    {imgSrc: "../resource/folder.png"},
    {imgSrc: "../resource/cerise.jpg"},
    {imgSrc: "../resource/ChatTim.jpg"},
    {imgSrc: "../resource/tetris.png"},
    {imgSrc: "../resource/shiva.jpg"},
    {imgSrc: "../resource/poop.jpg"},
    {imgSrc: "../resource/monkey.jpg"},
    {imgSrc: "../resource/Kenny.png"},
    {imgSrc: "../resource/Geneviève.jpg"},
    {imgSrc: "../resource/eagle.jpg"},
    {imgSrc: "../resource/berlin.jpg"},
    {imgSrc: "../resource/couscous.jpg"},
    {imgSrc: "../resource/dora.jpg"},
    {imgSrc: "../resource/kassos.jpg"},
    {imgSrc: "../resource/kawai.png"},
    {imgSrc: "../resource/manipulator.jpg"},
    {imgSrc: "../resource/minions.jpg"},
    {imgSrc: "../resource/vache.jpeg"},
    {imgSrc: "../resource/pokeball.png"}]);